### ISSUE TITLE
Ability to use a fork of react-native 

### ISSUE THREAD

**Issue by unknownexception** [rnplay/rnplay-web#1]
Does it make sense? ![image](https://cloud.githubusercontent.com/assets/1004115/7951633/4ceac5ea-09c3-11e5-87a7-de55a5f86595.png)
It would be useful to demonstrate some feature in pull request.

**Comment by jsierles** [comment]
This would be complicated today, as we run the packager web server just as you would in development. So we'd have to run a separate packager instance for every fork. As the packager evolves, this may get easier.

One way this could be done now is to allow uploading of a full bundle file to be served directly to the application. We plan to add this feature soon so people can just upload a whole bundled app for testing. However, editing would not be supported in this case.

In theory, later we could support building a production bundle like this from the editor contents and fork of react-native on the server :)

**Comment by unknownexception** [comment]
`uploading of a full bundle file` sounds reasonable enough for me.
