### ISSUE TITLE
Why don't add sign in with github?

### ISSUE THREAD

**Issue by soliury** [rnplay/rnplay-web#12]
I think use github to sign in is better.

**Comment by jozan** [comment]
Thanks for suggestion @soliury!

I really like to have Github sign in as well and @jsierles has some plans for it. Currently we're focusing on improving the user interface and user experience of the editor which takes a while.

**Comment by soliury** [comment]
ok, I see.

**Comment by jsierles** [comment]
I can add this fairly quickly, but the issue is tying existing user accounts to the Github login. Twitter doesn't provide an email address, unfortunately, so many accounts don't have it!

**Comment by jsierles** [comment]
This is coming in today's redesign launch.
