### ISSUE TITLE
require a title for an app

### ISSUE THREAD

**Issue by jsierles** [rnplay/rnplay-web#13]
Most apps are called "Sample App". We want these to be recognizable by their names :)

**Comment by jozan** [comment]
For some people it is really hard to come up with names. Some good examples would be nice for them. :)

**Comment by jsierles** [comment]
I don't mean names like that. Just 'scrollable view with button' or 'PR #4233 shadow test'

**Comment by jozan** [comment]
Yes, those are good examples! Not everyone knows what would be a good name.
