### ISSUE TITLE
Bundle is not dynamically generating

### ISSUE THREAD

**Issue by traic** [rnplay/rnplay-web#21]
What exactly am I mapping to ngrok, the location of the app_js files? I get a NOT FOUND html landing page in the simulator after setting up ngrok subdomain, and mapping it to localhost:8080. I have nginx server set up to point to app_js. I'm a little unclear how to get past this set up step.

**Comment by jsierles** [comment]
I'd recommend using the editor-redesign branch, which has fixed a number of issues with this setup. There, you can use the foreman gem to run all the pieces you need. ```gem install foreman``` then run ```foreman start```. Now the web app is at localhost:34560 and the packager at 34580. You want to forward ngrok to port 34580, and make sure to put your ngrok subdomain in the .env file. Finally, restart foreman and you should be good to go!

**Comment by jozan** [comment]
Just a heads up but `editor-redesign` branch is now merged into `master`.

**Comment by traic** [comment]
much better, it's almost running correctly, still get the red screen on the appetize.io preview tool though, console logs outputs "2015-09-17 00:17:56.745 [warn][tid:NSOperationQueue 0x7fd08a525820 :: NSOperation 0x7fd08c100d00 (QOS: UTILITY)][RCTDevMenu.m:211] RCTSourceCode module scriptURL has not been set"

**Comment by traic** [comment]
webpack-devserver seems to be running ok, and I'm guessing this is being used to bundle up the JS with react:

http://kevinold.com/2015/02/04/configure-webpack-dev-server-and-react-hot-loader-with-ruby-on-rails.html

**Comment by jsierles** [comment]
Maybe you could clarify what your use case is for running this locally? Running over ngrok will be very slow for actually working on a project.

When you say 'bundles are not packaging' are you referring to your React Native javascript apps?

**Comment by traic** [comment]
yes, the index.ios.js file is not packaging into index.ios.bundle, therefore not displaying in the appetize.io previewer. if ngrok is not required, and I can bypass it, that works for me. I'm still ramping up on the project, so not sure how to configure it 100% yet.

**Comment by traic** [comment]
ok I think the issue maybe I was using nginx to set up a web server for the app_js folder. I should be running a node server off of the folder right? Any specific instructions on how I should be setting this up properly? the index.io.bundle URL is not be called properly, because I don't have a react-native container running the node app.

**Comment by jsierles** [comment]
First you should use the master branch, and make sure you have run ```npm install``` both in the root dir, and inside app_js. The latter will ensure your packager runs correctly.

Then I highly recommend using foreman to run the app. Foreman will use the Procfile to run all the pieces you need (packager, webpack server and Rails).

**Comment by traic** [comment]
yep, got it work, I was running ngrok on the wrong port, thanks man!
