### ISSUE TITLE
List of usability issues on the site and editor

### ISSUE THREAD

**Issue by jozan** [rnplay/rnplay-web#27]
**Pages:**
- [ ] No contact details / page
- [ ] No 404 page
- [ ] Navigation doesn't show which is current page, also bolder first item is confusing #25
- [ ] No good signs that user is logged in, only small gear icon on the right #25
- [ ] Sign in doesn't redirect to page where user originally wanted to sign in

**Editor:**
- [ ] QR Modal: App Store Badge is not clickable...
- [ ] Title doesn't give any indication when it's saved
- [ ] No confirmation when user closes the browser tab with unsaved changes
- [ ] Vim bindings are broken

**Comment by jbbr** [comment]
Also confusing:
It's not possible to add new files in the web interface - but when forking an app with more than 1 file it's possible to edit multiple files in the fork.

**Comment by ColinEberhardt** [comment]
Totally agree with @jbbr - I have no idea how to add new files!

**Comment by jsierles** [comment]
Thanks for the comments! This was really an experimental feature - the apps that have multiple files are actually clonable git repositories. We never intended to create a full online editor - only to work via git. But I can see how this is confusing.

Right now, we're working on a private service, similar to the Playground, which will work entirely off Github webhooks. The work done there will likely make its way back here.

Any help is appreciated!

**Comment by jsierles** [comment]
Going to close this out pending a general upcoming rewrite of the Playground to address stability and usability.
