### ISSUE TITLE
The appropriate `index` file should be selected based on the current simulator

### ISSUE THREAD

**Issue by dsibiski** [rnplay/rnplay-web#30]
**Test path**: If I set an app to use the Android simulator, it still shows the `index.ios.js` file by default in the editor. This can be confusing if the user doesn't notice the files in the sidebar. They might be editing the iOS index file expecting the simulator to update but it doesn't.

**Proposed Solution**: The correct `index` file should be auto-loaded in the editor based on the type of simulator that is selected.

**Comment by jsierles** [comment]
Done!

**Comment by jsierles** [comment]
Reopening - this still needs to be implemented for viewers. Only works for authors now.

**Comment by jozan** [comment]
Buggy on authors.

**Reproduce steps:**

1. Select a file that is not `index.*.js`
2. Switch simulator
3. File doesn't change in editor
