### ISSUE TITLE
5minfork feature

### ISSUE THREAD

**Issue by getsetbro** [rnplay/rnplay-web#34]
Like 5minfork.com the rnplay site could fork a repo for 5 minutes and display it on the site. After 5 minutes it would be dropped.

**Comment by jozan** [comment]
Sorry fo late answer!
Anyhow, fascianting idea, what would be your use cases for this?

**Comment by getsetbro** [comment]
Developers could build and leave the code in the repo. When someone is ready to see that code in rnplay the they load it up in the 5minfork feature of rnplay and view it for 5 minutes.

**Comment by jozan** [comment]
Ah, seems like a private repo with viewing access only for a limited time, right? Currently we don't have any plans to add private repos into RNPlay.

Closing this issue for now.
