### ISSUE TITLE
Build Search option for Rnplay web version 

### ISSUE THREAD

**Issue by saurshaz** [rnplay/rnplay-web#35]
Would be really nice to have the search api integrated on rnplay.org

As i understand the functionality shall be there from the API. it shall be a quick one.

**Comment by jsierles** [comment]
I agree this would be great to have. Any interest in helping out?

**Comment by saurshaz** [comment]
I'll try to. help me out with the endpoint url for search. i guess only the UI work might be needed. I'm no expert at rails (work on Java/python/node and JS mostly) . but from what i understand It shall be all front-end. i am at the reactiflux channnel , we can probably continue the conversation there.

**Comment by jsierles** [comment]
@saurshaz Any interest in this still?

**Comment by saurshaz** [comment]
@jsierles interest yes, short of time to devote guys.

**Comment by jsierles** [comment]
OK, thanks!

**Comment by jsierles** [comment]
Going to close this for now. Feel free to open again later if someone starts on this!
