### ISSUE TITLE
Embeds?

### ISSUE THREAD

**Issue by bsudekum** [rnplay/rnplay-web#36]
@jsierles is there a way to embed the output from the simulator?

**Comment by jsierles** [comment]
At the moment we're only given permission graciously by Appetize to use the simulator output on rnplay.org - these are real simulators running on macs, which normally come at cost. However, I'll ask about this possibility! It may not be an issue as long as usage doesn't spike too much. Where would you want to use it?

**Comment by bsudekum** [comment]
Blogging on mapbox.com. This could generate some decent traffic however...

**Comment by jsierles** [comment]
If the goal is more a product demo, one option here would be to use appetize.io independently from the playground. They only charge after 100 minutes so it might be enough to try. Also means you can customize the embed and such without asking us to implement anything.
