### ISSUE TITLE
Saved apps have been deleted?

### ISSUE THREAD

**Issue by cem2ran** [rnplay/rnplay-web#38]
Yesterday I logged in with "Sign in with Github", which I honestly cannot remember if existed before, but I noticed that none of my saved apps were there anymore. I should note, that the last time i logged in was before the android support was added. So today I tried password login and was logged into the same account with the Sample App i created yesterday.

Another thing. I also noticed that when I logged in with github I was not redirected back to rnplay.

So my concern is that either: 
1. My account was overwritten when I logged in with github.
2. There has been some data loss on the server. 
3. That I have very bad memory and may have deleted all apps on my account, most likely by accident, but I'm pretty confident that this is not the case.

**Comment by jsierles** [comment]
Previously we had Twitter authentication, but decided to replace it with Github If you didn't enter your email back then, you may have two accounts in place. If you know the name of any of your previous apps, I can link them to your new account.

Feel free to send your email address (both the one used for password login, and your github email) to info@rnplay.org, and I'll take a look at your account. We can continue the discussion there!
