### ISSUE TITLE
The state of the project and contribution

### ISSUE THREAD

**Issue by gitim** [rnplay/rnplay-web#41]
Hi! Thanks for rnplayground, I am very excited about your project, it is really cool. Could you tell what is the state of the project, is it in development? Because there were some issues with pushing reps into rnplayground git. Also I'd like to contribute to the project, are there any issues, that I can try to solve?

**Comment by jsierles** [comment]
Hello! Git push is currently disabled. We can't support it because there were too many module conflicts between projects. However, we would like to support pushing fully compiled javascript bundles in the future. Maybe you would like to help there?
