### ISSUE TITLE
Cannot copy code?

### ISSUE THREAD

**Issue by rclai** [rnplay/rnplay-web#43]
I'm finding that it is impossible to copy the code via command + C. Is this intentional? In addition, right-clicking shows a disabled Copy command.

Great resource btw.

**Comment by christopherdro** [comment]
@rclai Is this your own app? If not, your going to have to fork the app first.

Editing is disabled on apps that are not yours.

**Comment by rclai** [comment]
It's not my own app but I'm not trying to edit, I'm just trying to copy.

**Comment by christopherdro** [comment]
@rclai Setting the input as disabled also prevents you from copying the content.

I see the issue with the app no longer being available. @jsierles Ideas on why forking this app would cause that to happen?

**Comment by jsierles** [comment]
There was a bug with forking apps. Forking should work now!

We'll look into the making it possible to copy code too. Thanks for the report.

**Comment by rclai** [comment]
Thanks guys this is awesome!

**Comment by nvcken** [comment]
Still cannot copy code. I think it's inconvenience

**Comment by jsierles** [comment]
This is finally fixed. Thanks for your patience!
