### ISSUE TITLE
Password reset issue

### ISSUE THREAD

**Issue by marcusmolchany** [rnplay/rnplay-web#46]
As a user who signed up with github I could not reset my password from the profile page.

I could however reset password and reset from the link in my email.

Not sure if this is the right place for this type of feedback. Love the tool!

**Comment by jsierles** [comment]
Thanks for the report. We'll look into it.

**Comment by alexmbp** [comment]
Btw, have a similar problem. When trying to sign in from the iOS App - always have 'wrong password' error.

**Comment by sghosh968** [comment]
@jsierles : I want to work on this if you haven't started with already.

**Comment by jsierles** [comment]
Go for it! Let me know if you need help getting setup locally.

**Comment by sghosh968** [comment]
Sure will let you know I need help with something, thanks.
