### ISSUE TITLE
Not working on Android

### ISSUE THREAD

**Issue by GeoffreyPlitt** [rnplay/rnplay-web#48]
Hey guys,

I've installed the android version from the app store. When I go to load most examples, I see RED error screens, as though these apps are trying to load in debug/local mode, instead of packaged/release bundles. So the app is currently not usable?

**Comment by jsierles** [comment]
Currently the native apps are not working with our new site. Hopefully soon we'll get a new version up based on Exponent.js.

**Comment by jsierles** [comment]
The new Android build is published on the Play Store now. Thanks!
