### ISSUE TITLE
TypeError in the simulator with almost all the apps

### ISSUE THREAD

**Issue by mahmoudfelfel** [rnplay/rnplay-web#5]
I've tried to use react-native play, but i'm getting this error with almost all the apps:
![screenshot from 2015-07-10 14 51 29](https://cloud.githubusercontent.com/assets/3989750/8617339/d505f5f4-2713-11e5-8b40-fc5edb84ecd2.png)

It was working fine before, like few days ago!

**Comment by jsierles** [comment]
Sorry about this - it's related to apps being pushed with conflicting React Native versions.

I just fixed this, and am adding another fix to prevent these apps from being pushed. Thanks for the heads up!
