### ISSUE TITLE
Android Preview gone ?

### ISSUE THREAD

**Issue by tfritsch-km** [rnplay/rnplay-web#50]
I can't see anymore the android/ios switch on the preview pane (iOS is now by default and the only choice).
This issue is related to commit https://github.com/rnplay/rnplay-web/commit/cfe042e172cfb13c143b055ac4c7691173e21a99 labelled "remove android support" but I can't see why this has been done ? Is there any plan on reactivating this ?

**Comment by jsierles** [comment]
Sorry for the trouble. We had some issues with the backend and had to disable it.

However, given my lack of time and working solo on this project, rnplay.org is going to be sunset in favor of a new project from the Expo people: https://sketch.expo.io. It runs much faster and is supported by their team. Check it out!

**Comment by tfritsch-km** [comment]
NP, thanks a lot for the great job on rnplay. Thanks for the link to sketch too, I didn't know it and it looks like what I need :)
Does that mean I should close this issue ?

**Comment by jsierles** [comment]
Yeah I'll close. thanks!
