### ISSUE TITLE
Ability to add other modules

### ISSUE THREAD

**Issue by skitterm** [rnplay/rnplay-web#6]
It would be great to be able to use an app that pulls in other modules. For example, I have an app that references https://github.com/alinz/react-native-webview-bridge. Any plans for this in the future?

**Comment by jsierles** [comment]
We're happy to add modules as they get requested. They can be available right away on the web, but only at release time for the App Store version. In theory it would be possible to automate this process in the future, once the module authors adopt a method for automating native code linking.

Anyway, I'll add this module for the 0.8 build, and close this PR when it's up.

**Comment by skitterm** [comment]
Ok. So the module will be there for the web, just not something viewable on the app, right? And if I wanted to add the module myself, I could just stick it in the root package.json, right?

**Comment by jsierles** [comment]
That won't work, because modules with native code need to be compiled into
the app. We have to built a new binary and upload it to the web. Then after
it's submitted to the app store, it will be available after approval.

**Comment by skitterm** [comment]
Ok. Here is the other module that I'd like to use: https://github.com/marcshilling/react-native-image-picker

Thanks for your help.

**Comment by jsierles** [comment]
These modules are installed and slated to go out with the next release!
