### ISSUE TITLE
Quick Toughts of rnplay.org

### ISSUE THREAD

**Issue by jozan** [rnplay/rnplay-web#8]
## Quick Toughts of rnplay.org

_@jsierles asked me on IRC if I could help with some of the UI issues the website is facing. So here is some quick thoughts about the website. I'm not a professional UI/UX designer so keep that in mind when reading this. Also, I try to get quickly to the point so wording may be direct, no offence._

We can all admit that the website is good but quite frustrating to use. I discussed with @jsierles about some pain points that needs to be addressed and based on them I collected my thoughs to this document. Rnplay.org has a good set of features and UI is almost there already.

The purpose of this document is to start a discussion.

## Inconsistency

The website already has some issues with inconsistency and more so in the future when new features get to see day light. For example it's hard to spot the difference between an action button and a link.

Inconsistency is a problem that needs to be addressed constantly and some sort of guidelines might be one approach.

## Discovery problems

Some features are hidden behind undocumented hotkeys or buttons that do not look like buttons.

- Action buttons that don't look like buttons (file drawer)
- Hidden editor actions (save, maybe more)

Editor has quite nice features already but it really lacks some. One of the biggest missing feature is feedback loop. It's not necessarily a feature but bunch of things giving constant visual feedback. Every meaningful action should have some kind of indicator that something is happening and has happened.

**Simple example of feedback loop when saving in editor**:

1. User triggers save (hotkey or button)
	- Editor performs save and refreshes simulator
	- Simulator gets refreshed
2. User gets notified a file is saved and simulator restarts

## The Biggest Pain Points

**Log viewer**, as of now, seems to log simulator events but it could be used to log events like save and similar so all events are logged in one place and not cluttered all around the UI.

**Save** and **Clone** buttons. Their placement is not ideal. Right now they are on top of simulator and user might confuse them to save simulator state not editor's content. Maybe a toolbar of some sort could solve these issues. Also sometimes buttons are there sometimes not, it's confusing. [Example](http://i.imgur.com/FQJjE3z.png) of better placement.

## Other things
404 Error: [https://rnplay.org/contact](https://rnplay.org/contact)

**Run on your device modal** is missing close button.

**Comment by jsierles** [comment]
Definitely agree that all of these are important points. Thanks for putting it all into words!

I'll get the contact page fixed. Perhaps we can split some of this up into separate issues?

**Comment by jozan** [comment]
Splitting these into separate issues is okay.

**Comment by jsierles** [comment]
We've got this!
